# Generated by Django 5.2.2 on 2026-03-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detailed_content',
            field=models.TextField(blank=True, help_text='Full detailed content for the dedicated service page'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL identifier (auto-generated if left blank)', max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='detailed_content',
            field=models.TextField(blank=True, help_text='Full content for the dedicated location page'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short description for list views'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='description',
            field=models.TextField(blank=True, help_text='Short description'),
        ),
    ]
