# Generated by Django 5.2.2 on 2026-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('resume_link', models.URLField(blank=True, help_text='Link to LinkedIn, Google Drive, or Portfolio', null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('INTERVIEWED', 'Interviewed'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='NEW', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
