# Generated by Django 5.2.2 on 2026-03-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='stat_clients',
            field=models.IntegerField(default=1500, help_text='Number of clients'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_retention',
            field=models.IntegerField(default=99, help_text='Client retention percentage'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_sqft',
            field=models.IntegerField(default=50, help_text='Millions of Sq Ft serviced'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_years',
            field=models.IntegerField(default=25, help_text='Years in business'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
