# Generated by Django 5.2.2 on 2026-03-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_stat_clients_sitesetting_stat_retention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_repeat_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='lifetime_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_review_link',
            field=models.URLField(blank=True, help_text='Link to your Google My Business review page', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default='638 Webster St. Suite 430, Oakland CA 94607', max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='info@24hfminc.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default='5104096697', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='24 Hours Facility Maintenance Inc.', max_length=200),
        ),
    ]
