# Generated by Django 5.2.2 on 2026-04-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_is_repeat_customer_booking_lifetime_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('before_image', models.ImageField(upload_to='gallery/')),
                ('after_image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Short description of the cleaning transformation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
