# Generated by Django 5.2.13 on 2026-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='24hrfacilitymaintenance@gmail.com', max_length=254),
        ),
    ]
