# Generated by Django 5.2.13 on 2026-07-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesetting_contact_email'),
        ('core', '0008_fix_booking_status_default'),
    ]

    operations = [
    ]
