# Generated by Django 5.2.17 on 2026-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20260722_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="gclid",
            field=models.CharField(
                blank=True,
                help_text="Google Ads click ID. Present when the lead came from a paid click.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="landing_page",
            field=models.CharField(
                blank=True,
                help_text="First page of the visit that produced this lead.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="referrer",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="booking",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="booking",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="utm_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="utm_term",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
