# Generated by Django 5.2.2 on 2026-09-01 16:02

from django.db import migrations, models

OLD_PHONE = '5104096697'
NEW_PHONE = '5109347490'
OLD_ADDRESS = '638 Webster St. Suite 430, Oakland CA 94607'
NEW_ADDRESS = '601 Willow St. Unit G, Alameda CA 94501'


def update_existing_contact_info(apps, schema_editor):
    SiteSetting = apps.get_model('core', 'SiteSetting')
    SiteSetting.objects.filter(contact_phone=OLD_PHONE).update(contact_phone=NEW_PHONE)
    SiteSetting.objects.filter(address=OLD_ADDRESS).update(address=NEW_ADDRESS)


def revert_existing_contact_info(apps, schema_editor):
    SiteSetting = apps.get_model('core', 'SiteSetting')
    SiteSetting.objects.filter(contact_phone=NEW_PHONE).update(contact_phone=OLD_PHONE)
    SiteSetting.objects.filter(address=NEW_ADDRESS).update(address=OLD_ADDRESS)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_gclid_booking_landing_page_booking_referrer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default=NEW_ADDRESS, max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default=NEW_PHONE, max_length=20),
        ),
        migrations.RunPython(update_existing_contact_info, revert_existing_contact_info),
    ]
