# Generated by Django 5.2.2 on 2026-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='close_convert_lead_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ga_client_id',
            field=models.CharField(blank=True, help_text='GA4 client ID captured at submission. Needed to report qualify_lead/close_convert_lead server-side.', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='qualify_lead_reported',
            field=models.BooleanField(default=False),
        ),
    ]
