"""
Django settings for janitorial_site project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&0_5#x$5)szut6m!g%m(e=@r*t^%_@095!i+!9gem=ti@ezy9w')

# SECURITY WARNING: don't run with debug turned on in production!
# Cast string 'True'/'False' from os.environ
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Tell Django it's secure when behind the Nginx/Cloudflare proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'core',
]

MIDDLEWARE = [
    'janitorial_site.middleware.MediaServeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'janitorial_site.middleware.AttributionMiddleware',
    'janitorial_site.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'janitorial_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
                'core.context_processors.google_tracking',
            ],
        },
    },
]

WSGI_APPLICATION = 'janitorial_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Override database settings if DATABASE_URL is provided in environment variables
if os.getenv('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise Configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ─── Security Headers (Production) ───────────────────────────────────────
# These settings harden the site against common attacks and satisfy audit tools.

# HSTS: Force browsers to always use HTTPS for 1 year, include subdomains
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# X-Content-Type-Options: Prevent MIME-type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# X-Frame-Options: Prevent clickjacking (already set by middleware, explicit here)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Referrer-Policy: Only send origin on cross-origin requests
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# SSL Redirect: Redirect all HTTP to HTTPS in production
SECURE_SSL_REDIRECT = bool(os.getenv('DATABASE_URL'))  # Only in production

# Secure cookies in production
SESSION_COOKIE_SECURE = bool(os.getenv('DATABASE_URL'))
CSRF_COOKIE_SECURE = bool(os.getenv('DATABASE_URL'))


# ─── Google Tracking (Analytics + Ads) ───────────────────────────────────
# GA4 measurement ID and Google Ads conversion ID are rendered into every page
# by the google_tracking context processor. Leave a value blank to disable
# that tag entirely.

GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID', 'G-JLBYG49T3E')
GOOGLE_ADS_CONVERSION_ID = os.getenv('GOOGLE_ADS_CONVERSION_ID', 'AW-1962616492')

# The conversion LABEL is specific to each conversion action and is only
# visible in the Google Ads UI (Goals > Conversions > your action > tag setup).
# It looks like 'AbC-D_efG-h12_34-567'. Without it, Google Ads records page
# views but cannot attribute a single conversion, so leads look like zero.
GOOGLE_ADS_LEAD_CONVERSION_LABEL = os.getenv(
    'GOOGLE_ADS_LEAD_CONVERSION_LABEL', ''
)
GOOGLE_ADS_CALL_CONVERSION_LABEL = os.getenv('GOOGLE_ADS_CALL_CONVERSION_LABEL', '')

# Google Tag Manager container. Kept alongside gtag.js so any tags already
# configured in the container keep working.
GOOGLE_TAG_MANAGER_ID = os.getenv('GOOGLE_TAG_MANAGER_ID', 'GTM-K3K8Z87F')


# ─── Email (lead notifications) ──────────────────────────────────────────
# Without these, form submissions are saved to the database but nobody is
# told about them. Set EMAIL_HOST_USER / EMAIL_HOST_PASSWORD in .env to turn
# notifications on. For Gmail, EMAIL_HOST_PASSWORD must be a 16-character
# App Password (https://myaccount.google.com/apppasswords), not the account
# password.

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))

# Brevo HTTPS API key, used only when EMAIL_BACKEND points at
# core.email_backends.BrevoAPIBackend. DigitalOcean blocks outbound SMTP on
# this droplet, so mail relays over port 443 instead. If that block is ever
# lifted, drop the EMAIL_BACKEND line from .env and the settings above take
# over again with no code change.
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'webmaster@localhost')

# Where new lead notifications are delivered. Comma-separated list; falls back
# to the SiteSetting contact email at send time when left blank.
LEAD_NOTIFICATION_EMAILS = [
    addr.strip()
    for addr in os.getenv('LEAD_NOTIFICATION_EMAILS', '').split(',')
    if addr.strip()
]

